-- 테이블들
-- 멤버, 메뉴 목록, 메뉴 상세, 1:1 문의, 
--

-- <CREATE>

CREATE TABLE MEMBER_TBL (
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PW VARCHAR2(20) NOT NULL,
    MEMBER_NAME VARCHAR2(15) NOT NULL,
    MEMBER_BIRTHDAY DATE NOT NULL,
    MEMBER_GENDER CHAR(6),
    MEMBER_EMAIL VARCHAR2(50),
    MEMBER_PHONE VARCHAR2(11),
    MEMBER_ADDRESS VARCHAR2(150)
);

CREATE TABLE BR_SYSTEM_TBL (
    BR_SYSTEM_ID VARCHAR2(20) PRIMARY KEY,
    BR_SYSTEM_PW VARCHAR2(20) NOT NULL,
    BR_SYSTEM_NAME VARCHAR2(15) NOT NULL
);

drop table SYSTEM_TBL;

delete MEMBER_TBL WHERE MEMBER_ID='brsystem';
insert into MEMBER_TBL values('brsystem', 'syspass', '관리자', '2000-01-01', null, null, null, null);
insert into BR_SYSTEM_TBL values('brsystem', 'syspass', '관리자');


CREATE TABLE BOARD_TBL (
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_SUBJECT VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR2(1500) NOT NULL,
    BOARD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    BOARD_UPDATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    BOARD_WRITER VARCHAR2(20) NOT NULL,
    BOARD_FILE_NAME VARCHAR2(100),
    BOARD_FILE_RENAME VARCHAR2(200),
    BOARD_FILE_PATH VARCHAR2(300),
    BOARD_FILE_LENGTH NUMBER
);


-- 메뉴 테이블(아이스크림, 케이크, 커피, 음료, 디저트)
CREATE TABLE MENU_TBL(
    MENU_PK_NAME VARCHAR2(20) PRIMARY KEY,
    MENU_NAME VARCHAR2(50),
    MENU_ENG_NAME VARCHAR2(20),
    MENU_EXPLAIN VARCHAR2(200),
    MENU_TYPE VARCHAR2(30) NOT NULL,
    MENU_FLAVOR VARCHAR2(40),
    MENU_HOT_ICE VARCHAR(3),
    MENU_PRICE NUMBER NOT NULL,
    MENU_IMG_NAME VARCHAR2(50),
    MENU_IMG_RENAME VARCHAR2(200),
    MENU_IMG_PATH VARCHAR2(300) NOT NULL,
    MENU_IMG_LENGTH NUMBER,
    MENU_CREATE DATE DEFAULT SYSDATE,
    MENU_UPDATE DATE DEFAULT SYSDATE,
    MENU_STATUS CHAR(1) DEFAULT 'Y'    
);

drop table MENU_TBL;
    
-- 아이스크림 테이블
CREATE TABLE ICECREAM_TBL(
    MENU_PK_NAME VARCHAR2(20) PRIMARY KEY,
    ICE_NAME VARCHAR2(40),
    ICE_ENG_NAME VARCHAR2(20),
    MENU_EXPLAIN VARCHAR2(200),
    MENU_TYPE VARCHAR2(15) NOT NULL,
    ICE_IMG_NAME VARCHAR2(50),
    ICE_IMG_RENAME VARCHAR2(200),
    ICE_IMG_PATH VARCHAR2(300) NOT NULL,
    ICE_IMG_LENGTH NUMBER,
    ICE_CREATE DATE DEFAULT SYSDATE,
    ICE_UPDATE DATE DEFAULT SYSDATE,
    ICE_STATUS CHAR(1) DEFAULT 'Y'
);

CREATE SEQUENCE SEQ_ICECREAM_NO;

drop table ICECREAM_TBL;


CREATE SEQUENCE SEQ_BOARD_NO;
--START WITH 1
--INCREMENT BY 1
--MAXVALUE 10000
--NOCYCLE
--NOCACHE;

--<INSERT>


INSERT INTO ICECREAM_TBL VALUES('ㄴㄴ', 'ㄴㄴ', '식별 - 비식별.png', 'p20230829172041.png', '../resources/productImgFiles/p20230829172041.png', 101385, DEFAULT, DEFAULT, 'Y'); 



INSERT INTO MEMBER_TBL VALUES('user01', 'pass01', '일번', '94/07/12', 'F', 'user01@gmail.com', '01011111111', '서울시 중구');
INSERT INTO MEMBER_TBL VALUES('user02', 'pass02', '이번', '00/05/10', 'M', 'user02@gmail.com', '01022222222', '서울시 동대문구');
INSERT INTO MEMBER_TBL VALUES('user03', 'pass03', '삼번', '93/07/07', 'F', 'user03@naver.com', '01033333333', '부산광역시 해운대구');
INSERT INTO MEMBER_TBL VALUES('user04', 'pass04', '사번', '90/06/17', 'F', 'user04@naver.com', '01044444444', '인천광역시 부천구');
INSERT INTO MEMBER_TBL VALUES('user05', 'pass05', '오번', '04/08/23', 'M', 'user05@gmail.com', '01055555555', '강원도 강릉시 화천군');
INSERT INTO MEMBER_TBL VALUES('user06', 'pass06', '육번', '96/03/06', 'F', 'user06@gmail.com', '01066666666', '서울시 성동구');
INSERT INTO MEMBER_TBL VALUES('user07', 'pass07', '칠번', '98/01/30', 'M', 'user07@naver.com', '01077777777', '제주특별자치도 서귀포시');
INSERT INTO MEMBER_TBL VALUES('user08', 'pass08', '팔번', '94/04/12', 'F', 'user08@daum.net', '01088888888', '서울시 서초구');
INSERT INTO MEMBER_TBL VALUES('user09', 'pass09', '구번', '01/12/04', 'F', 'user09@naver.com', '01099999999', '서울시 서대문구');
INSERT INTO MEMBER_TBL VALUES('user10', 'pass10', '십번', '99/11/18', 'F', 'user10@gmail.com', '01010101010', '전라남도 나주시 나주시');

INSERT INTO BOARD_TBL VALUES(SEQ_BOARD_NO.NEXTVAL, 'user01의 문의글1', 'user01의 문의글', DEFAULT, 'user01');
INSERT INTO BOARD_TBL VALUES(SEQ_BOARD_NO.NEXTVAL, 'user01의 문의글2', 'user01의 문의글', DEFAULT, 'user01', '일번');
INSERT INTO BOARD_TBL VALUES(SEQ_BOARD_NO.NEXTVAL, 'user01의 문의글3', 'user01의 문의글', DEFAULT, 'user01', '일번');
INSERT INTO BOARD_TBL VALUES(SEQ_BOARD_NO.NEXTVAL, 'user01의 문의글4', 'user01의 문의글', DEFAULT, 'user01', '일번');
INSERT INTO BOARD_TBL VALUES(SEQ_BOARD_NO.NEXTVAL, 'user01의 문의글5', 'user01의 문의글', DEFAULT, 'user01', '일번');
INSERT INTO BOARD_TBL VALUES(SEQ_BOARD_NO.NEXTVAL, 'user01의 문의글6', 'user01의 문의글', DEFAULT, 'user01', '일번');
INSERT INTO BOARD_TBL VALUES(SEQ_BOARD_NO.NEXTVAL, 'user01의 문의글7', 'user01의 문의글', DEFAULT, 'user01', '일번');
INSERT INTO BOARD_TBL VALUES(SEQ_BOARD_NO.NEXTVAL, 'user01의 문의글9', 'user01의 문의글', DEFAULT, 'user01', '일번');

INSERT INTO BOARD_TBL VALUES(SEQ_BOARD_NO.NEXTVAL, 'user10의 문의글9', 'user10의 문의글', DEFAULT, 'user10', '십번');

--<SELECT>

SELECT * FROM MEMBER_TBL;
SELECT * FROM MENU_TBL;
SELECT * FROM ICECREAM_TBL;
SELECT * FROM BOARD_TBL;
SELECT COUNT(*) FROM BOARD_TBL;
SELECT * FROM MEMBER_TBL;
SELECT COUNT(*) FROM BOARD_TBL WHERE BOARD_WRITER = 'user01';

SELECT * FROM USER_SEQUENCES;

SELECT * FROM MENU_TBL WHERE MENU_TYPE = 'iceCream' ORDER BY MENU_NAME ASC;

SELECT * FROM (SELECT ROW_NUMBER() OVER(ORDER BY BOARD_NO DESC) ROW_NUM, BOARD_NO, 
BOARD_DATE, BOARD_SUBJECT FROM BOARD_TBL WHERE BOARD_WRITER= 'user10');

SELECT COUNT(*) FROM MENU_TBL JOIN ICECREAM_TBL USING (MENU_TYPE) WHERE MENU_TYPE='iceCream';
SELECT COUNT(*) FROM ICECREAM_TBL WHERE MENU_TYPE='iceCream';

--<DROP>

DROP TABLE MEMBER_TBL;
DROP TABLE MENU_TBL;
DROP TABLE MENU_ICECREAM_TBL;
DROP TABLE BOARD_TBL;


DROP SEQUENCE SEQ_BOARD_NO;

SELECT MEMBER_NAME FROM MEMBER_TBL JOIN BOARD_TBL ON MEMBER_ID = BOARD_WRITER WHERE BOARD_WRITER = 'user01';



SELECT BOARD_SUBJECT, BOARD_CONTENT, MEMBER_NAME FROM BOARD_TBL
INNER JOIN MEMBER_TBL ON BOARD_WRITER = MEMBER_ID
WHERE BOARD_WRITER = 'user01';


SELECT * FROM(
SELECT ROW_NUMBER() OVER(ORDER BY NOTICE_NO DESC) ROW_NUM, NOTICE_TBL.* FROM NOTICE_TBL)
WHERE ROW_NUM BETWEEN 1 AND 10;

SELECT * FROM (SELECT ROW_NUMBER() OVER(ORDER BY BOARD_NO DESC) ROW_NUM, BOARD_NO, BOARD_DATE, 
BOARD_SUBJECT, BOARD_WRITER_NAME FROM BOARD_TBL WHERE BOARD_WRITER = 'user10') ;


SELECT * FROM (SELECT ROW_NUMBER() OVER(ORDER BY BOARD_NO DESC) ROW_NUM, BOARD_DATE, BOARD_SUBJECT FROM BOARD_TBL INNER JOIN MEMBER_TBL ON BOARD_WRITER = MEMBER_ID WHERE BOARD_WRITER = 'user01');

SELECT COUNT(*) FROM BOARD_TBL;

SELECT * FROM (SELECT ROW_NUMBER() OVER(ORDER BY BOARD_NO DESC) ROW_NUM, BOARD_NO, BOARD_DATE, 
BOARD_SUBJECT, BOARD_WRITER_NAME FROM BOARD_TBL WHERE BOARD_WRITER = 'user10');
SELECT * FROM (SELECT ROW_NUMBER() OVER(ORDER BY BOARD_NO DESC) ROW_NUM, BOARD_NO, BOARD_DATE, 
BOARD_SUBJECT, BOARD_WRITER_NAME FROM BOARD_TBL WHERE BOARD_WRITER = 'user10');
SELECT * FROM BOARD_TBL WHERE BOARD_WRITER = 'user10';



commit;
rollback;




