INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('그린티', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\그린티.png', '엄선된 녹차를 사용한 싱그러운 그린티 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('뉴욕 치즈 케이크', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\뉴욕_치즈케이크.png', '부드럽게 즐기는 뉴욕식 정통 치즈케이크 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('디노젤리', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\디노_젤리.png', '파인애플 & 그린 애플 아이스크림에 알록달록 공룡젤리가 콩콩!');
INSERT INTO ICECREAM_TBL VALUES('라이언 망고 마카롱', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\라이언_망고_마카롱.png', '애플망고 & 망고 아이스크림과 카이막 맛 아이스크림에 달콤한 마카롱, 애플망고가 어우러진 맛');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\레드_라즈베리_소르베.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');
INSERT INTO ICECREAM_TBL VALUES('31요거트', 'D:\summerworkspace\BRSpring\src\main\webapp\resources\image\product\icecream\31요거트.png', '유산균이 살아있는 오리지널 요거트 아이스크림');